'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace eCAMS
    
    Partial Public Class incpPageHeader
        
        '''<summary>
        '''lblLoginInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLoginInfo As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''pnlMenu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlMenu As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''hlnkHome control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hlnkHome As Global.System.Web.UI.WebControls.HyperLink
        
        '''<summary>
        '''hlnkLogout control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hlnkLogout As Global.System.Web.UI.WebControls.HyperLink
    End Class
End Namespace
