var newWindow; function popupwindow(a) { makeNewWindow(a, "Details", "toolbar=no,location=no,directories=no,status=yes,menubar=no,scrollbars=yes,resizable=yes,width=700,height=700,alwaysRaised"); return !1 } function makeNewWindow(a, b, c) { !newWindow || newWindow.closed ? (newWindow = window.open(a, b, c), newWindow.opener || (newWindow.opener = window)) : (newWindow.location = a, newWindow.focus()); newWindow.focus() } function VerifyDate(a, b) { b.IsValid = validateDate(b.Value) }
function VerifyTime(a, b) { b.IsValid = validateTime(b.Value) } function VerifyTradingHours(a, b) { b.IsValid = validateTradingHours(b.Value) || "close" == b.Value.toLowerCase() || "closed" == b.Value.toLowerCase() } function validateDate(a) { rex = /^(0?[1-9]|[12][0-9]|3[01])\/(1[0-2]|0?[1-9])\/\d\d$/; return rex.test(a) }
function validateTime(a) { var b = []; if (isNaN(a) || 4 != a.length) return !1; a = a.slice(0, 1) + a.slice(1, 2) + ":" + a.slice(2, 3) + a.slice(3, 4) + ":00"; b = a.match(/^(\d\d):(\d\d):(\d\d)$/); return null != b && 0 <= b[1] && 24 > b[1] && 0 <= b[2] && 60 > b[2] && 0 <= b[3] && 60 > b[3] ? !0 : !1 } function validateTradingHours(a) { return 9 == a.length && a.slice(4,5) == "-" && (validateTime(a.slice(0, 4)) && validateTime(a.slice(5, 9))) && a.slice(0, 4) < a.slice(5, 9) ? !0 : !1 }
function highlightRowViaCheckBox(a, b) { var c; if (a.parentNode) for (c = a.parentNode; "tr" != c.nodeName.toLowerCase(); ) c = c.parentNode; else if (a.parentElement) for (c = a.parentElement; "tr" != c.tagName.toLowerCase(); ) c = c.parentElement; c && (a.checked ? (c.oldBackgroundColor = c.style.backgroundColor, c.style.backgroundColor = b) : c.style.backgroundColor = c.oldBackgroundColor) } function DoesControlExist(a, b) { return null == a.getElementById(b) ? !1 : !0 }
function Left(a, b) { return 0 >= b ? "" : b > String(a).length ? a : String(a).substring(0, b) } function Right(a, b) { if (0 >= b) return ""; if (b > String(a).length) return a; var c = String(a).length; return String(a).substring(c, c - b) }
function getDocumentAll(a, b) { for (var c = a.getElementsByTagName("input"), e = [], d = 0; d < c.length; d++) "*" == Right(b, 1) ? "*" == Left(b, 1) ? 0 < String(c[d].name).indexOf(Right(Left(b, b.length - 1), b.length - 2)) && e.push(c[d]) : Left(c[d].name, b.length - 1) == Left(b, b.length - 1) && e.push(c[d]) : c[d].name == b && e.push(c[d]); return e }
function validateSofwareApplicationSelection(a) { var b = !1, c = getDocumentAll(a, "*chkSoftwareApplication_*"); for (a = 0; a < c.length; a++) if (!c[a].disabled && c[a].checked) { b = !0; break } 0 == c.length && (b = !0); return b } function validateBulkSelection(a) { var b = !1, c = getDocumentAll(a, "chkBulk"); for (a = 0; a < c.length; a++) if (!c[a].disabled && c[a].checked) { b = !0; break } return b }
function selectAllchkBulk(a) { var b = getDocumentAll(a, "chkBulk"); for (a = 0; a < b.length; a++) !b[a].disabled && !b[a].checked && (b[a].checked = !0, highlightRowViaCheckBox(b[a], "#fff4c2")); return !1 } function isPositiveIntegerOrZero(a) { return "" == a || isNaN(a) || 0 <= a.indexOf("-") || 0 <= a.indexOf(".") ? !1 : !0 } function isPositiveInteger(a) { return "" == a || isNaN(a) || 0 <= a.indexOf("-") || 0 <= a.indexOf(".") || 0 == a ? !1 : !0 } function VerifyPositiveIntegerOrZero(a, b) { b.IsValid = isPositiveIntegerOrZero(b.Value) }
function stripHTMLTag(a) { var b = document.createElement("DIV"); b.innerHTML = a; return b.textContent || b.innerText };
function ChangeCheckBoxBackColor(e, t, n) { var r = document.getElementById(e); if (r.checked == true) { r.parentElement.style.backgroundColor = t } else { r.parentElement.style.backgroundColor = n } };
function ValidateCheckedAtLeastOne(e) { for (var t = document.getElementById(e).getElementsByTagName("input"), n = 0; n < t.length; n++)if (t[n].checked) return !0; return !1 }