'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace eCAMS
    
    Partial Public Class FSPMain
        
        '''<summary>
        '''UserPasswordAlert1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UserPasswordAlert1 As Global.UserControl_UserPasswordAlert
        
        '''<summary>
        '''hlSwapJob control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hlSwapJob As Global.System.Web.UI.WebControls.HyperLink
        
        '''<summary>
        '''hlInstallJob control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hlInstallJob As Global.System.Web.UI.WebControls.HyperLink
        
        '''<summary>
        '''hlDeinstallJob control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hlDeinstallJob As Global.System.Web.UI.WebControls.HyperLink
        
        '''<summary>
        '''hlUpgradeJob control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hlUpgradeJob As Global.System.Web.UI.WebControls.HyperLink
        
        '''<summary>
        '''hlPickPackTask control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hlPickPackTask As Global.System.Web.UI.WebControls.HyperLink
        
        '''<summary>
        '''hlStockInTransit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hlStockInTransit As Global.System.Web.UI.WebControls.HyperLink
        
        '''<summary>
        '''hlFSPException control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hlFSPException As Global.System.Web.UI.WebControls.HyperLink
        
        '''<summary>
        '''hlStockReturned control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hlStockReturned As Global.System.Web.UI.WebControls.HyperLink
        
        '''<summary>
        '''panelStockTake control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents panelStockTake As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''hlStockTake control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hlStockTake As Global.System.Web.UI.WebControls.HyperLink
    End Class
End Namespace
