'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace eCAMS

    Partial Public Class LogJob

        '''<summary>
        '''panelHelpTipMID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents panelHelpTipMID As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''ltlHelpTipMID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ltlHelpTipMID As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''panelHelpTipPhone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents panelHelpTipPhone As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''ltlHelpTipPhone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ltlHelpTipPhone As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''panelHelpTradingHours control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents panelHelpTradingHours As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''ltlHelpTradingHours control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ltlHelpTradingHours As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblFormTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFormTitle As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtClientID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtClientID As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''txtJobTypeID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtJobTypeID As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''placeholderMsg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents placeholderMsg As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''panelTIDPage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents panelTIDPage As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblClientID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblClientID As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''cboClientID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboClientID As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblTID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTID As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtTID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTID As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblTIDHint control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTIDHint As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''btnTIDGo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnTIDGo As Global.System.Web.UI.HtmlControls.HtmlInputSubmit

        '''<summary>
        '''panelFullPage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents panelFullPage As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''panelUpgradeJob control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents panelUpgradeJob As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''Label24 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label24 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtOldTerminalID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtOldTerminalID As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Label25 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label25 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''cboOldDeviceType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboOldDeviceType As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblTerminalID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTerminalID As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtTerminalID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTerminalID As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''panelFDIAdditionalInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents panelFDIAdditionalInfo As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''Label50 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label50 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtCustomerNumber1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCustomerNumber1 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Label2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtProblemNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtProblemNumber As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''divProblemNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divProblemNumber As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''panelProjectNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents panelProjectNo As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblProjectNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblProjectNo As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''cboProjectNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboProjectNo As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''panelJobMethodAndTerminalType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents panelJobMethodAndTerminalType As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblJobMethod control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblJobMethod As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''cboJobMethod control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboJobMethod As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''Label4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label4 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''cboDeviceType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboDeviceType As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''panelCallTypeSymptomFault control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents panelCallTypeSymptomFault As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''UpdatePanel1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''Label26 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label26 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''cboCallType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboCallType As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''Label27 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label27 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''cboSymptom control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboSymptom As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblErrorCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblErrorCode As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''cboFault control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboFault As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblErrorCodeQty control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblErrorCodeQty As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ddlQuantity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlQuantity As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''btnAddErroCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnAddErroCode As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''lblErrorCodeLine control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblErrorCodeLine As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''gvErrorCodes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gvErrorCodes As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''lblErrorCodeMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblErrorCodeMessage As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblErrorCodeFormMandatory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblErrorCodeFormMandatory As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''panelAdditionalServiceType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents panelAdditionalServiceType As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''Label30 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label30 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''cboAdditionalServiceType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboAdditionalServiceType As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''panelCAIC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents panelCAIC As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''Label41 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label41 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtCAIC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCAIC As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''panelCustomerName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents panelCustomerName As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''Label49 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label49 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''cboCustomerName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboCustomerName As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''Label3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label3 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblMIDPrefix control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMIDPrefix As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtMerchantID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMerchantID As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Label5 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label5 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Label6 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label6 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAddress As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Label7 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label7 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtAddress2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAddress2 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Label8 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label8 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtCity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCity As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Label11 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label11 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''cboState control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboState As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''Label9 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label9 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtPostcode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPostcode As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Label31 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label31 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtRegion control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtRegion As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''UpdatePanelSurburbAndPostcode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelSurburbAndPostcode As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''panelServiceStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents panelServiceStatus As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''Label29 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label29 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtServiceStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtServiceStatus As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''Label10 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label10 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtContact control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtContact As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''divContact control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divContact As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''Label12 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label12 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtPhoneNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPhoneNumber As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''divPhone1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divPhone1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''Label13 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label13 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtPhoneNumber2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPhoneNumber2 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''panelNABAdditionalInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents panelNABAdditionalInfo As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''Label42 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label42 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtContactEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtContactEmail As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Label43 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label43 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtBankersEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtBankersEmail As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Label44 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label44 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtMerchantEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMerchantEmail As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''div1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents div1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''Label45 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label45 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtCustomerNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCustomerNumber As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''div2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents div2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''Label46 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label46 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtAltMerchantID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAltMerchantID As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''div3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents div3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''Label28 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label28 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtBusinessActivity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtBusinessActivity As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''panelTransendID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents panelTransendID As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''Label38 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label38 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtTransendID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTransendID As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Label32 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label32 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''Label33 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label33 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtJobNote control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtJobNote As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Label14 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label14 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtSpecInstruct control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSpecInstruct As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Label15 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label15 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''chbUrgent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chbUrgent As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''panelLostStolen control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents panelLostStolen As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''Label48 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label48 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''chbLostStolen control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chbLostStolen As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblLostStolenSel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLostStolenSel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''panelSiteEquiptment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents panelSiteEquiptment As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''Label47 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label47 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''grdSiteEquiptment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdSiteEquiptment As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''panelTechAtt control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents panelTechAtt As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblTechToAttWithoutCall control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTechToAttWithoutCall As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''chbTechToAttWithoutCall control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chbTechToAttWithoutCall As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''panelInstallDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents panelInstallDate As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''Label17 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label17 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtInstallDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtInstallDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''divInstallDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divInstallDate As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''Label18 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label18 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''UpdatePanel2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanel2 As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''panelGetTradingHoursFromSite control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents panelGetTradingHoursFromSite As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''Label40 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label40 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''btnGetTradingHoursFromSite control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnGetTradingHoursFromSite As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''Label19 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label19 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''divTradingHourMFHint control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divTradingHourMFHint As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''Label21 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label21 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtTradingHoursMon control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTradingHoursMon As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''divTradingHourMon control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divTradingHourMon As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''Label34 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label34 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtTradingHoursTue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTradingHoursTue As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''divTradingHourTue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divTradingHourTue As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''Label35 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label35 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtTradingHoursWed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTradingHoursWed As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''divTradingHourWed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divTradingHourWed As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''Label36 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label36 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtTradingHoursThu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTradingHoursThu As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''divTradingHourThu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divTradingHourThu As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''Label37 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label37 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtTradingHoursFri control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTradingHoursFri As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''divTradingHourFri control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divTradingHourFri As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''Label22 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label22 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtTradingHoursSat control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTradingHoursSat As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Label23 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label23 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtTradingHoursSun control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTradingHoursSun As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Label20 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label20 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''PanelUpdateSiteTradingHours control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PanelUpdateSiteTradingHours As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''Label39 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label39 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''chkUpdateSiteTradingHours control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkUpdateSiteTradingHours As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''panelCommsMethod control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents panelCommsMethod As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''Label16 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label16 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''cboLineType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboLineType As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''panelDialPrefix control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents panelDialPrefix As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''Label1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtDialPrefix control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDialPrefix As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''panelFeature control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents panelFeature As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''panelComponent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents panelComponent As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''btnSave control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSave As Global.System.Web.UI.HtmlControls.HtmlInputSubmit

        '''<summary>
        '''panelAcknowledge control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents panelAcknowledge As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblAcknowledge control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAcknowledge As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''rfvTID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvTID As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''ValidationSummary1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ValidationSummary1 As Global.System.Web.UI.WebControls.ValidationSummary

        '''<summary>
        '''rfvTerminalID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvTerminalID As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''rfvDeviceType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvDeviceType As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''rfvCallType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvCallType As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''rfvSymptom control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvSymptom As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''rfvFault control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvFault As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''rfvCAIC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvCAIC As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''rfvMerchantID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvMerchantID As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''rfvProblemNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvProblemNumber As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''rfvName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvName As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''rfvAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvAddress As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''rfvAddress2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvAddress2 As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''rfvCity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvCity As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''rfvPostcode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvPostcode As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''rfvContact control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvContact As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''rfvPhoneNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvPhoneNumber As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''rfvInstallDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvInstallDate As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''rfvOldTerminalID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvOldTerminalID As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''rfvErrorCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvErrorCode As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''rfvTradingHoursMon control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvTradingHoursMon As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''rfvTradingHoursTue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvTradingHoursTue As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''rfvTradingHoursWed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvTradingHoursWed As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''rfvTradingHoursThu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvTradingHoursThu As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''rfvTradingHoursFri control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvTradingHoursFri As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''rfvTradingHoursSat control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvTradingHoursSat As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''rfvTradingHoursSun control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvTradingHoursSun As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''rfvMerchantEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvMerchantEmail As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''rfvCustomerNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvCustomerNumber As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''rfvAltMerchantID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvAltMerchantID As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''cvTradingHoursMon control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cvTradingHoursMon As Global.System.Web.UI.WebControls.CustomValidator

        '''<summary>
        '''cvTradingHoursTue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cvTradingHoursTue As Global.System.Web.UI.WebControls.CustomValidator

        '''<summary>
        '''cvTradingHoursWed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cvTradingHoursWed As Global.System.Web.UI.WebControls.CustomValidator

        '''<summary>
        '''cvTradingHoursThu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cvTradingHoursThu As Global.System.Web.UI.WebControls.CustomValidator

        '''<summary>
        '''cvTradingHoursFri control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cvTradingHoursFri As Global.System.Web.UI.WebControls.CustomValidator

        '''<summary>
        '''cvTradingHoursSat control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cvTradingHoursSat As Global.System.Web.UI.WebControls.CustomValidator

        '''<summary>
        '''cvTradingHoursSun control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cvTradingHoursSun As Global.System.Web.UI.WebControls.CustomValidator

        '''<summary>
        '''cvTH control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cvTH As Global.System.Web.UI.WebControls.CustomValidator

        '''<summary>
        '''cvSWApp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cvSWApp As Global.System.Web.UI.WebControls.CustomValidator

        '''<summary>
        '''revInstallDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents revInstallDate As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''revPhone1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents revPhone1 As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''revPhone2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents revPhone2 As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''revTerminalIDBoQ control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents revTerminalIDBoQ As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''revOldTerminalIDBoQ control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents revOldTerminalIDBoQ As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''revMerchantIDBoQ control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents revMerchantIDBoQ As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''revMerchantIDCBA control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents revMerchantIDCBA As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''revMerchantIDTYR control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents revMerchantIDTYR As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''revTerminalIDCBA control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents revTerminalIDCBA As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''revJobNoteMaxLength control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents revJobNoteMaxLength As Global.System.Web.UI.WebControls.RegularExpressionValidator
    End Class
End Namespace
