'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace eCAMS
    
    Partial Public Class Merchant
        
        '''<summary>
        '''lblFormTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFormTitle As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''txtClientID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtClientID As Global.System.Web.UI.WebControls.HiddenField
        
        '''<summary>
        '''placeholderMsg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents placeholderMsg As Global.System.Web.UI.WebControls.PlaceHolder
        
        '''<summary>
        '''panelTIDPage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents panelTIDPage As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''lblClientID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblClientID As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''cboClientID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboClientID As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''lblTID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTID As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''txtTID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTID As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''btnTIDGo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnTIDGo As Global.System.Web.UI.HtmlControls.HtmlInputSubmit
        
        '''<summary>
        '''panelFullPage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents panelFullPage As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''lblTerminalID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTerminalID As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''txtTerminalID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTerminalID As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''Label3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label3 As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''txtMerchantID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMerchantID As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''Label5 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label5 As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''txtName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtName As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''Label6 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label6 As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''txtAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAddress As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''Label7 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label7 As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''txtAddress2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAddress2 As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''Label8 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label8 As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''txtCity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCity As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''Label11 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label11 As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''cboState control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboState As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''Label9 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label9 As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''txtPostcode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPostcode As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''Label10 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label10 As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''txtContact control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtContact As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''divContact control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divContact As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''Label12 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label12 As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''txtPhoneNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPhoneNumber As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''divPhone1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divPhone1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''Label13 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label13 As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''txtPhoneNumber2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPhoneNumber2 As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''Label19 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label19 As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''divTradingHourMFHint control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divTradingHourMFHint As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''Label21 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label21 As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''txtTradingHoursMon control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTradingHoursMon As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''divTradingHourMon control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divTradingHourMon As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''Label34 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label34 As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''txtTradingHoursTue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTradingHoursTue As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''divTradingHourTue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divTradingHourTue As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''Label35 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label35 As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''txtTradingHoursWed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTradingHoursWed As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''divTradingHourWed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divTradingHourWed As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''Label36 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label36 As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''txtTradingHoursThu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTradingHoursThu As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''divTradingHourThu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divTradingHourThu As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''Label37 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label37 As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''txtTradingHoursFri control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTradingHoursFri As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''divTradingHourFri control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divTradingHourFri As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''Label22 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label22 As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''txtTradingHoursSat control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTradingHoursSat As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''Label23 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label23 As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''txtTradingHoursSun control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTradingHoursSun As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''Label20 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label20 As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''Label15 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label15 As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''chbApplyTheChange control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chbApplyTheChange As Global.System.Web.UI.WebControls.CheckBox
        
        '''<summary>
        '''btnSave control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSave As Global.System.Web.UI.HtmlControls.HtmlInputSubmit
        
        '''<summary>
        '''panelAcknowledge control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents panelAcknowledge As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''lblAcknowledge control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAcknowledge As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''rfvTID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvTID As Global.System.Web.UI.WebControls.RequiredFieldValidator
        
        '''<summary>
        '''ValidationSummary1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ValidationSummary1 As Global.System.Web.UI.WebControls.ValidationSummary
        
        '''<summary>
        '''rfvTerminalID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvTerminalID As Global.System.Web.UI.WebControls.RequiredFieldValidator
        
        '''<summary>
        '''rfvMerchantID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvMerchantID As Global.System.Web.UI.WebControls.RequiredFieldValidator
        
        '''<summary>
        '''rfvName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvName As Global.System.Web.UI.WebControls.RequiredFieldValidator
        
        '''<summary>
        '''rfvAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvAddress As Global.System.Web.UI.WebControls.RequiredFieldValidator
        
        '''<summary>
        '''rfvAddress2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvAddress2 As Global.System.Web.UI.WebControls.RequiredFieldValidator
        
        '''<summary>
        '''rfvCity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvCity As Global.System.Web.UI.WebControls.RequiredFieldValidator
        
        '''<summary>
        '''rfvPostcode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvPostcode As Global.System.Web.UI.WebControls.RequiredFieldValidator
        
        '''<summary>
        '''rfvContact control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvContact As Global.System.Web.UI.WebControls.RequiredFieldValidator
        
        '''<summary>
        '''rfvPhoneNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvPhoneNumber As Global.System.Web.UI.WebControls.RequiredFieldValidator
        
        '''<summary>
        '''rfvTradingHoursMon control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvTradingHoursMon As Global.System.Web.UI.WebControls.RequiredFieldValidator
        
        '''<summary>
        '''rfvTradingHoursTue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvTradingHoursTue As Global.System.Web.UI.WebControls.RequiredFieldValidator
        
        '''<summary>
        '''rfvTradingHoursWed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvTradingHoursWed As Global.System.Web.UI.WebControls.RequiredFieldValidator
        
        '''<summary>
        '''rfvTradingHoursThu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvTradingHoursThu As Global.System.Web.UI.WebControls.RequiredFieldValidator
        
        '''<summary>
        '''rfvTradingHoursFri control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvTradingHoursFri As Global.System.Web.UI.WebControls.RequiredFieldValidator
        
        '''<summary>
        '''rfvTradingHoursSat control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvTradingHoursSat As Global.System.Web.UI.WebControls.RequiredFieldValidator
        
        '''<summary>
        '''rfvTradingHoursSun control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvTradingHoursSun As Global.System.Web.UI.WebControls.RequiredFieldValidator
        
        '''<summary>
        '''cvTradingHoursMon control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cvTradingHoursMon As Global.System.Web.UI.WebControls.CustomValidator
        
        '''<summary>
        '''cvTradingHoursTue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cvTradingHoursTue As Global.System.Web.UI.WebControls.CustomValidator
        
        '''<summary>
        '''cvTradingHoursWed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cvTradingHoursWed As Global.System.Web.UI.WebControls.CustomValidator
        
        '''<summary>
        '''cvTradingHoursThu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cvTradingHoursThu As Global.System.Web.UI.WebControls.CustomValidator
        
        '''<summary>
        '''cvTradingHoursFri control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cvTradingHoursFri As Global.System.Web.UI.WebControls.CustomValidator
        
        '''<summary>
        '''cvTradingHoursSat control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cvTradingHoursSat As Global.System.Web.UI.WebControls.CustomValidator
        
        '''<summary>
        '''cvTradingHoursSun control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cvTradingHoursSun As Global.System.Web.UI.WebControls.CustomValidator
        
        '''<summary>
        '''revPhone1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents revPhone1 As Global.System.Web.UI.WebControls.RegularExpressionValidator
        
        '''<summary>
        '''revPhone2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents revPhone2 As Global.System.Web.UI.WebControls.RegularExpressionValidator
    End Class
End Namespace
