'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace eCAMS
    
    Partial Public Class mpBulletin
        
        '''<summary>
        '''hdBulletinID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdBulletinID As Global.System.Web.UI.WebControls.HiddenField
        
        '''<summary>
        '''placeholderBody control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents placeholderBody As Global.System.Web.UI.WebControls.PlaceHolder
        
        '''<summary>
        '''PanelButonAccept control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PanelButonAccept As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''btnAccept control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnAccept As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''btnDecline control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnDecline As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''PanelButtonOK control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PanelButtonOK As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''btnOK control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnOK As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
