'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace eCAMS

    Partial Public Class mpFSPDownload

        '''<summary>
        '''videoPlayerId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents videoPlayerId As Global.System.Web.UI.HtmlControls.HtmlVideo

        '''<summary>
        '''videoIframeId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents videoIframeId As Global.System.Web.UI.HtmlControls.HtmlIframe
    End Class
End Namespace
