'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace eCAMS
    
    Partial Public Class mpFSPStockReceived
        
        '''<summary>
        '''panelEdit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents panelEdit As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''cboDepot control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboDepot As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''txtDateReceived control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDateReceived As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''btnSave control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''panelScan control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents panelScan As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''Panel2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Panel2 As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''txtSerial control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSerial As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''txtBatchID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtBatchID As Global.System.Web.UI.WebControls.HiddenField
        
        '''<summary>
        '''btnSaveSerial control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSaveSerial As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''RepeaterDevice control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RepeaterDevice As Global.System.Web.UI.WebControls.Repeater
        
        '''<summary>
        '''panelAcknowledge control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents panelAcknowledge As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''rfvSerial control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvSerial As Global.System.Web.UI.WebControls.RequiredFieldValidator
        
        '''<summary>
        '''cvDateReceived control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cvDateReceived As Global.System.Web.UI.WebControls.CustomValidator
        
        '''<summary>
        '''rfvDateReceived control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvDateReceived As Global.System.Web.UI.WebControls.RequiredFieldValidator
        
        '''<summary>
        '''ValidationSummary1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ValidationSummary1 As Global.System.Web.UI.WebControls.ValidationSummary
    End Class
End Namespace
