'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace eCAMS
    
    Partial Public Class mpFSPJobList
        
        '''<summary>
        '''panelJobList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents panelJobList As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''Repeater1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Repeater1 As Global.System.Web.UI.WebControls.Repeater
        
        '''<summary>
        '''cboSort control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboSort As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''lblListInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblListInfo As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
